name: Check Style


on: [push, pull_request]

jobs:

  style:
 
    runs-on: ubuntu-latest
 
    steps:
    uses: shivammathur/setup-php@v2
    with: php-version: '7.4'
    - uses: actions/checkout@v1

    - name: Only fetch Style PHP submodule
      run: git submodule update --init -- .style

    - name: Install latest PHP-CS-Fixer
      run: wget https://cs.symfony.com/download/php-cs-fixer-v2.phar

    - name: Run Checks
      run: PHP_CS_FIXER_IGNORE_ENV=1 php php-cs-fixer-v2.phar fix --config=.style/.php_cs -v --dry-run --diff --allow-risky=yes .
      