name: Run Tests

on: [push, pull_request]

jobs:

  test:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true

    - name: "Install PHP with extensions"
      uses: "shivammathur/setup-php@v1"
      with:
        php-version: "8.0"
        coverage: "pcov"

    - name: "Cache dependencies installed with composer"
      uses: "actions/cache@v1"
      with:
        path: "~/.composer/cache"
        key: "php8.0-composer-highest-${{ hashFiles('**/composer.json') }}"
        restore-keys: "php8.0-composer-highest-"

    - name: "Run tests with phpunit/phpunit"
      run: "vendor/bin/phpunit --coverage-clover=coverage.xml"
      