name: Run Tests

on: [push, pull_request]

jobs:

  test:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true

    - uses: shivammathur/setup-php@v1

    - name: Run Tests
      run: phpdbg -qrr phpunit.phar tests --configuration tests/phpunit.xml
      